const MILLISECONDS_PER_SECOND = 1000
const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * 60
const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_MINUTE * 60
const MILLISECONDS_PER_DAY = MILLISECONDS_PER_HOUR * 24
const MILLISECONDS_PER_WEEK = MILLISECONDS_PER_DAY * 7
const MILLISECONDS_PER_YEAR = MILLISECONDS_PER_WEEK * 52

const INFURA_URI = "https://mainnet.infura.io/v3"
const ETHERSCAN_API_URI = "https://api.etherscan.io/api"
const C = {
  STATUS_ACTIVE: 1,
  STATUS_INACTIVE: 0,
  STATUS_DELETED: -1,

  ROLE_SYSTEM: "$system",
  ROLE_EVERYONE: "$everyone",
  ROLE_AUTHENTICATED: "$authenticated",
  ROLE_ADMINISTRATOR: "administrator",
  ROLE_USER: "user",

  VISIBILITY_PRIVATE: "private",
  VISIBILITY_PROTECTED: "protected",
  VISIBILITY_PUBLIC: "public",
  VISIBILITY_PUBLISHED: "published",

  TOKEN_TYPE_VERIFICATION: "verification",
  TOKEN_TYPE_PASSWORDLESS: "passwordless",
  TOKEN_TYPE_PASSWORD_RESET: "password-reset",
  TOKEN_TYPE_API_KEY: "api-key"
}

export default {
  ...C,

  TOKEN_TYPES: [
    C.TOKEN_TYPE_VERIFICATION,
    C.TOKEN_TYPE_PASSWORDLESS,
    C.TOKEN_TYPE_PASSWORD_RESET,
    C.TOKEN_TYPE_API_KEY
  ],

  MILLISECONDS_PER_SECOND,
  MILLISECONDS_PER_MINUTE,
  MILLISECONDS_PER_HOUR,
  MILLISECONDS_PER_DAY,
  MILLISECONDS_PER_WEEK,
  MILLISECONDS_PER_YEAR,

  ETHERSCAN_API_URI,
  INFURA_URI
}
