const MILLISECONDS_PER_SECOND = 1000
const MILLISECONDS_PER_MINUTE = MILLISECONDS_PER_SECOND * 60
const MILLISECONDS_PER_HOUR = MILLISECONDS_PER_MINUTE * 60
const MILLISECONDS_PER_DAY = MILLISECONDS_PER_HOUR * 24
const MILLISECONDS_PER_WEEK = MILLISECONDS_PER_DAY * 7
const MILLISECONDS_PER_YEAR = MILLISECONDS_PER_WEEK * 52

const INFURA_URI = "https://mainnet.infura.io/v3"
const ETHERSCAN_API_URI = "https://api.etherscan.io/api"

export default {
  MILLISECONDS_PER_SECOND,
  MILLISECONDS_PER_MINUTE,
  MILLISECONDS_PER_HOUR,
  MILLISECONDS_PER_DAY,
  MILLISECONDS_PER_WEEK,
  MILLISECONDS_PER_YEAR,

  ETHERSCAN_API_URI,
  INFURA_URI
}
