version: "3.8"

services:
  # cron:
  #   build: .
  #   image: volatiliy-services
  #   container_name: cron
  #   env_file: docker-compose.env
  #   environment:
  #     DOCKER_BUILDKIT: 1
  #     TRANSPORTER: nats://nats:4222
  #     SERVICES: cron.service.js
  #     SSH_AUTH_SOCK: "${SSH_AUTH_SOCK}"
  #   links:
  #     - nats
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - nats
  #     - postgresd

  nats:
    image: nats:2
    container_name: nats
    ports:
      - '4222:4222'
    restart: unless-stopped
    command:
      - '-m'
      - '8222'
      - '--debug'
    labels:
      - "traefik.enable=false"

  postgresd:
    container_name: postgresd
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379"
    volumes:
      - redis_data:/var/lib/redis/data

  moleculer-services:
    build:
      context: .
    image: volatility-services-dev
    container_name: instrument_info
    env_file: docker-compose.env
    restart: on-failure
    environment:
      DOCKER_BUILDKIT: 1
      SERVICES: instrument_info,ingest,index,ws
      SSH_AUTH_SOCK: /ssh-agent
    links:
      - nats
      - postgresd
      - redis
    volumes:
      - ~/.aws/:/root/.aws/
      - ./:/app
      - ~/.ssh:/root/.ssh:ro
      - $SSH_AUTH_SOCK:/ssh-agent
    depends_on:
      - nats
      - postgresd
      - redis

volumes:
  postgres_data:
  redis_data:
