version: "3.8"

# environment:
#   - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/<NAME_OF_SECRET>
services:
  cron:
    build: .
    image: 994224827437.dkr.ecr.us-east-2.amazonaws.com/volatility-services/backend:latest
    x-aws-pull_credentials: arn:aws:secretsmanager:us-east-2:994224827437:secret:dev/docker/ecr-AUOGC7
    container_name: cron
    env_file: docker-compose.env
    environment:
      SERVICES: cron
    links:
      - nats
    # volumes:
    #   - ./:/app
    depends_on:
      - nats
      - postgresd

  index:
    build:
      context: .
    container_name: index
    image: 994224827437.dkr.ecr.us-east-2.amazonaws.com/volatility-services/backend:latest
    x-aws-pull_credentials: arn:aws:secretsmanager:us-east-2:994224827437:secret:dev/docker/ecr-AUOGC7
    env_file: docker-compose.env
    environment:
      SERVICES: index
    links:
      - nats
      - postgresd
    depends_on:
      - ingest

  instrument_info:
    build:
      context: .
    image: 994224827437.dkr.ecr.us-east-2.amazonaws.com/volatility-services/backend:latest
    x-aws-pull_credentials: arn:aws:secretsmanager:us-east-2:994224827437:secret:dev/docker/ecr-AUOGC7
    container_name: instrument_info
    env_file: docker-compose.env
    environment:
      SERVICES: instrument_info
      REDIS_DB: 0
    links:
      - nats
    depends_on:
      - nats

  ingest:
    build:
      context: .
    image: 994224827437.dkr.ecr.us-east-2.amazonaws.com/volatility-services/backend:latest
    x-aws-pull_credentials: arn:aws:secretsmanager:us-east-2:994224827437:secret:dev/docker/ecr-AUOGC7
    container_name: ingest
    env_file: docker-compose.env
    restart: on-failure
    environment:
      SERVICES: ingest
    links:
      - nats
    depends_on:
      - nats
      - instrument_info

  ws:
    build:
      context: .
    image: 994224827437.dkr.ecr.us-east-2.amazonaws.com/volatility-services/backend:latest
    x-aws-pull_credentials: arn:aws:secretsmanager:us-east-2:994224827437:secret:dev/docker/ecr-AUOGC7
    container_name: ws
    env_file: docker-compose.env
    ports:
      - 3000:3000
    environment:
      SERVICES: ws
    links:
      - nats
    depends_on:
      - nats

  nats:
    # platform: linux/amd64
    image: nats:2.7.2
    container_name: nats
    env_file: docker-compose.env
    ports:
      - '4222:4222'
    restart: unless-stopped
    command:
      - '-m'
      - '8222'
      - '--debug'

  postgresd:
    # platform: linux/amd64
    container_name: postgresd
    image: postgres:12.10
    env_file: docker-compose.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2.6
    # image: arm64v8/redis:6.2.6
    container_name: redis
    env_file: docker-compose.env
    ports:
      - "6379"
    volumes:
      - redis_data:/var/lib/redis/data
volumes:
  postgres_data:
  redis_data:
