version: "3.8"

services:
  # cron:
  #   build: .
  #   image: volatiliy-services
  #   container_name: cron
  #   env_file: docker-compose.env
  #   environment:
  #     DOCKER_BUILDKIT: 1
  #     TRANSPORTER: nats://nats:4222
  #     SERVICES: cron.service.js
  #     SSH_AUTH_SOCK: "${SSH_AUTH_SOCK}"
  #   links:
  #     - nats
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - nats
  #     - postgresd
  nats:
    # platform: linux/amd64
    image: nats:2.7.2
    container_name: nats
    ports:
      - '4222:4222'
    restart: unless-stopped
    command:
      - '-m'
      - '8222'
      - '--debug'
    labels:
      - "traefik.enable=false"

  postgresd:
    # platform: linux/amd64
    container_name: postgresd
    image: postgres:12.10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      # - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    # platform: linux/arm64
    image: arm64v8/redis:6.2.6
    container_name: redis
    environment:
      - REDIS_PASSWORD='redis-password'
    ports:
      - "6379"
    volumes:
      - redis_data:/var/lib/redis/data

  index:
    container_name: index
    build:
      context: .
      # dockerfile: Dockerfile.slim
    image: volatility-services
    env_file: docker-compose.env
    environment:
      SERVICES: index
    links:
      - nats
      - postgresd
    volumes:
      - ~/.aws:/home/node/.aws
      # - ./:/app
      # - ./:/usr/src/app
    depends_on:
      - ingest

  instrument_info:
    build:
      context: .
      # dockerfile: Dockerfile.slim
    image: volatility-services
    container_name: instrument_info
    env_file: docker-compose.env
    environment:
      SERVICES: instrument_info
      REDIS_DB: 0
    links:
      - nats
    volumes:
      - ~/.aws:/home/node/.aws
      # - ./:/app
      # - ./:/usr/src/app
    depends_on:
      - nats

  ingest:
    build:
      context: .
      # dockerfile: Dockerfile.slim
    image: volatility-services
    container_name: ingest
    env_file: docker-compose.env
    restart: on-failure
    environment:
      SERVICES: ingest
    links:
      - nats
    volumes:
      - ~/.aws:/home/node/.aws
      # - ./:/app
      # - ./:/usr/src/app
    depends_on:
      - nats
      - instrument_info

  ws:
    build:
      context: .
      # dockerfile: Dockerfile.slim
    image: volatility-services
    container_name: ws
    env_file: docker-compose.env
    ports:
      - 3000:3000
    environment:
      SERVICES: ws
    links:
      - nats
    volumes:
      - ~/.aws:/home/node/.aws
      # - ./:/app
      # - ./:/usr/src/app
    depends_on:
      - nats

volumes:
  postgres_data:
  redis_data:
