version: "3.8"

services:
  tokens:
    build: .
    container_name: tokens
    image: volatility-services:latest
    env_file: docker-compose.env
    environment:
      SERVICES: tokens
    networks:
      - vg-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - nats
      - postgresd
      - redis
  cron:
    build: .
    image: volatility-services:latest
    container_name: cron
    env_file: docker-compose.env
    environment:
      SERVICES: cron
    networks:
      - vg-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - nats
      - postgresd

  index:
    build: .
    container_name: index
    image: volatility-services:latest
    env_file: docker-compose.env
    environment:
      SERVICES: index
    networks:
      - vg-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - ingest

  instrument_info:
    build: .
    image: volatility-services:latest
    container_name: instrument_info
    env_file: docker-compose.env
    environment:
      SERVICES: instrument_info
      REDIS_DB: 0
    depends_on:
      - nats
    networks:
      - vg-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  ingest:
    build: .
    image: volatility-services:latest
    container_name: ingest
    env_file: docker-compose.env
    # restart: on-failure
    environment:
      SERVICES: dist/ingest
    # links:
    #   - nats
    networks:
      - vg-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - nats
      - instrument_info

  ws:
    build: .
    image: volatility-services:latest
    container_name: ws
    env_file: docker-compose.env
    ports:
      - 3000:3000
    environment:
      SERVICES: ws
    networks:
      - vg-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - nats

  nats:
    # platform: linux/amd64
    image: public.ecr.aws/docker/library/nats:2.7.2
    container_name: nats
    env_file: docker-compose.env
    ports:
      - '4222:4222'
    command:
      - '-m'
      - '8222'
      - '--debug'
    networks:
      - vg-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  postgresd:
    # platform: linux/amd64
    container_name: postgresd
    image: public.ecr.aws/bitnami/postgresql:12.10.0
    env_file: docker-compose.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # - postgres_data:/var/lib/postgresql/data
      # - ./postgres/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vg-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  redis:
    image: public.ecr.aws/docker/library/redis:6.2
    # image: redis:6.2.6
    # image: arm64v8/redis:6.2.6
    container_name: redis
    env_file: docker-compose.env
    ports:
      - "6379"
    volumes:
      - redis_data:/var/lib/redis/data
    networks:
      - vg-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
  redis_data:

networks:
  vg-network:
    driver: overlay
